baseURL: "https://lexiconium.github.io/"
title: "What Did I Say?"
paginate: 5
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "What Did I Say?"
  author: "Minsoo Kim"
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  UseHugoToc: false
  showtoc: true
  tocopen: true

  homeInfoParams:
    Title: "I Said..."
    Content: >
        뭐라고 했었는지 기억하는 공간.

  socialIcons:
    - name: github
      url: "https://github.com/lexiconium"
    - name: email
      url: "mailto:min-soo.kim@outlook.kr"
